### ISSUE TITLE
AuthorizationService.GenerateClaims - add scope UsersRead to regular users

### ISSUE THREAD

**Issue by GhiocelAndrei** [GhiocelAndrei/IssueTrackerAPI#23]
https://github.com/GhiocelAndrei/IssueTrackerAPI/pull/19#discussion_r1271846882

Users should be able to list all users to re-assign issues.
To be reviewed when adding external token provider.

**Comment by cristi-paraschiv** [comment]
@GhiocelAndrei is this still needed, now that we moved to external auth?
please close if not needed anymore

**Comment by GhiocelAndrei** [comment]
This isn't needed since we are using external auth
