### ISSUE TITLE
Feature: Sprints

### ISSUE THREAD

**Issue by cristi-paraschiv** [GhiocelAndrei/IssueTrackerAPI#26]
Introduce new concept: Sprint

Sprints table:
- Id
- Name
- Description
- StartDate
- EndDate
- ICreation/ModificationTracking

Issues table:
- SprintId (nullable)

Sprint operations: CRUD
Issue operations: assign sprint (update)

Extra endpoints:
```GET issues/sprint/{id}```
```POST sprints/{id}/close```
```
POST sprints/createWithIssues
{
	"Issues": [ Id1, Id2, ... ]
}
```

**Comment by GhiocelAndrei** [comment]
Solved in PR #32
