### ISSUE TITLE
Feature: external IDs

### ISSUE THREAD

**Issue by cristi-paraschiv** [GhiocelAndrei/IssueTrackerAPI#28]
Issues should have an external ID (different than the one in the DB) based on project code and an internally managed sequence `{ProjectCode}-{Sequence}`.

E.g.: 

Project code: HDENS

Issues:
Id: 1, ExternalId: HDENS-3
Id: 2, ExternalId: HDENS-4
Id: 3, ExternalId: HDENS-5

All public endpoints should use the external ID when working with issues.

**Comment by GhiocelAndrei** [comment]
Feature added in PR #34
