### ISSUE TITLE
Database migrations test

### ISSUE THREAD

**Issue by cristi-paraschiv** [GhiocelAndrei/IssueTrackerAPI#46]
A test will be created that will assert the idempotency of the migrations.
The test should run the following sequence:
- create an empty database
- run all migrations Up
- run all migrations Down
- run all migrations Up

There should be no error thrown during this test.

Should use a SQL server instance (not in-memory, as that uses SQLite)

**Comment by GhiocelAndrei** [comment]
Added database migrations test in #48
